version: '7.3'

excluded:
  - var
  - vendor/aws/aws-sdk-php
  - vendor/aws/aws-sdk-php-symfony
  - vendor/bin/jp.php
  - vendor/cloudinary/cloudinary_php
  - vendor/clue/stream-filter
  - vendor/composer
  - vendor/doctrine/annotations
  - vendor/doctrine/cache
  - vendor/doctrine/collections
  - vendor/doctrine/common
  - vendor/doctrine/data-fixtures
  - vendor/doctrine/dbal
  - vendor/doctrine/doctrine-bundle
  - vendor/doctrine/doctrine-cache-bundle
  - vendor/doctrine/doctrine-fixtures-bundle
  - vendor/doctrine/doctrine-migrations-bundle
  - vendor/doctrine/event-manager
  - vendor/doctrine/inflector
  - vendor/doctrine/instantiator
  - vendor/doctrine/lexer
  - vendor/doctrine/migrations
  - vendor/doctrine/orm
  - vendor/doctrine/persistence
  - vendor/doctrine/reflection
  - vendor/drewm/mailchimp-api
  - vendor/egulias/email-validator
  - vendor/fig/http-message-util
  - vendor/fig/link-util
  - vendor/firebase/php-jwt
  - vendor/friendsofphp/php-cs-fixer
  - vendor/friendsofsymfony/oauth-server-bundle
  - vendor/friendsofsymfony/oauth2-php
  - vendor/friendsofsymfony/rest-bundle
  - vendor/giggsey/libphonenumber-for-php
  - vendor/giggsey/locale
  - vendor/google/auth
  - vendor/google/cloud-core
  - vendor/google/cloud-storage
  - vendor/google/crc32
  - vendor/guzzlehttp/guzzle
  - vendor/guzzlehttp/promises
  - vendor/guzzlehttp/psr7
  - vendor/helpscout/api
  - vendor/http-interop/http-factory-guzzle
  - vendor/incenteev/composer-parameter-handler
  - vendor/jdorn/sql-formatter
  - vendor/jean85/pretty-package-versions
  - vendor/kreait/clock
  - vendor/kreait/firebase-php
  - vendor/kreait/firebase-tokens
  - vendor/kreait/gcp-metadata
  - vendor/ktamas77/firebase-php
  - vendor/lcobucci/jwt
  - vendor/league/flysystem
  - vendor/lexik/jwt-authentication-bundle
  - vendor/michelf/php-markdown
  - vendor/monolog/monolog
  - vendor/mtdowling/jmespath.php
  - vendor/myclabs/deep-copy
  - vendor/namshi/jose
  - vendor/nelmio/cors-bundle
  - vendor/nelmio/api-doc-bundle
  - vendor/ocramius/package-versions
  - vendor/ocramius/proxy-manager
  - vendor/paragonie/random_compat
  - vendor/phar-io/manifest
  - vendor/phar-io/version
  - vendor/php-amqplib/php-amqplib
  - vendor/php-amqplib/rabbitmq-bundle
  - vendor/php-cs-fixer/diff
  - vendor/php-http/client-common
  - vendor/php-http/curl-client
  - vendor/php-http/discovery
  - vendor/php-http/httplug
  - vendor/php-http/message
  - vendor/php-http/message-factory
  - vendor/php-http/promise
  - vendor/psr/cache
  - vendor/psr/container
  - vendor/psr/http-client
  - vendor/psr/http-factory
  - vendor/psr/http-message
  - vendor/psr/link
  - vendor/psr/log
  - vendor/psr/simple-cache
  - vendor/phpdocumentor/reflection-common
  - vendor/phpdocumentor/reflection-docblock
  - vendor/phpdocumentor/type-resolver
  - vendor/phpspec/prophecy
  - vendor/phpunit/php-code-coverage
  - vendor/phpunit/php-file-iterator
  - vendor/phpunit/php-text-template
  - vendor/phpunit/php-timer
  - vendor/phpunit/php-token-stream
  - vendor/phpunit/phpunit
  - vendor/psr/http-message
  - vendor/ql/uri-template
  - vendor/psr/log
  - vendor/ralouphie/getallheaders
  - vendor/ramsey/uuid
  - vendor/raptor/php-migration-helper
  - vendor/riverline/multipart-parser
  - vendor/rize/uri-template
  - vendor/sebastian/code-unit-reverse-lookup
  - vendor/sebastian/comparator
  - vendor/sebastian/diff
  - vendor/sebastian/environment
  - vendor/sebastian/exporter
  - vendor/sebastian/global-state
  - vendor/sebastian/object-enumerator
  - vendor/sebastian/object-reflector
  - vendor/sebastian/recursion-context
  - vendor/sebastian/resource-operations
  - vendor/sebastian/type
  - vendor/sebastian/version
  - vendor/sensio/distribution-bundle
  - vendor/sensio/framework-extra-bundle
  - vendor/sensio/generator-bundle
  - vendor/sensiolabs/security-checker
  - vendor/sentry/sdk
  - vendor/sentry/sentry-symfony
  - vendor/sentry/sentry
  - vendor/shuber/curl
  - vendor/skyeng/auth-bundle
  - vendor/skyeng/common-bundle
  - vendor/skyeng/php-lemmatizer
  - vendor/superbalist/flysystem-google-storage
  - vendor/swiftmailer/swiftmailer
  - vendor/symfony/http-client
  - vendor/symfony/http-client-contracts
  - vendor/symfony/mime
  - vendor/symfony/monolog-bundle
  - vendor/symfony/phpunit-bridge
  - vendor/symfony/polyfill-apcu
  - vendor/symfony/polyfill-ctype
  - vendor/symfony/polyfill-iconv
  - vendor/symfony/polyfill-intl-idn
  - vendor/symfony/polyfill-intl-icu
  - vendor/symfony/polyfill-mbstring
  - vendor/symfony/polyfill-php56
  - vendor/symfony/polyfill-php70
  - vendor/symfony/polyfill-php72
  - vendor/symfony/polyfill-php73
  - vendor/symfony/polyfill-util
  - vendor/symfony/swiftmailer-bundle
  - vendor/symfony/symfony
  - vendor/theseer/tokenizer
  - vendor/twig/twig
  - vendor/webmozart/assert
  - vendor/welp/mailchimp-bundle
  - vendor/willdurand/jsonp-callback-validator
  - vendor/willdurand/negotiation
  - vendor/zendframework/zend-code
  - vendor/zendframework/zend-diactoros
  - vendor/zendframework/zend-eventmanager

packages:
  aws/aws-sdk-php: '3.112.5'
  aws/aws-sdk-php-symfony: '1.3.0'
  cloudinary/cloudinary_php: '1.14.0'
  clue/stream-filter: '1.4.1'
  composer/semver: '1.5.0'
  composer/xdebug-handler: '1.3.3'
  doctrine/annotations: '1.7.0'
  doctrine/cache: '1.8.0'
  doctrine/collections: '1.6.2'
  doctrine/common: '2.11.0'
  doctrine/data-fixtures: '1.3.2'
  doctrine/dbal: '2.9.2'
  doctrine/doctrine-bundle: '1.11.2'
  doctrine/doctrine-cache-bundle: '1.3.5'
  doctrine/doctrine-fixtures-bundle: '3.2.2'
  doctrine/doctrine-migrations-bundle: '1.3.2'
  doctrine/event-manager: '1.0.0'
  doctrine/inflector: '1.3.0'
  doctrine/instantiator: '1.2.0'
  doctrine/lexer: '1.1.0'
  doctrine/migrations: '1.8.1'
  doctrine/orm: '2.6.3'
  doctrine/persistence: '1.1.1'
  doctrine/reflection: '1.0.0'
  drewm/mailchimp-api: '2.5.4'
  egulias/email-validator: '2.1.11'
  fig/http-message-util: '1.1.3'
  fig/link-util: '1.0.0'
  firebase/php-jwt: '5.0.0'
  friendsofphp/php-cs-fixer: '2.15.3'
  friendsofsymfony/oauth-server-bundle: '2.0.0'
  friendsofsymfony/oauth2-php: '1.2.3'
  friendsofsymfony/rest-bundle:
    version: '2.5.0'
    message: 'Warning (minor severity): friendsofsymfony/rest-bundle does not have version that is fully compatible with PHP 7.3 (latest known 2.5.0)'
  giggsey/libphonenumber-for-php: '8.10.19'
  giggsey/locale: '1.7.1'
  google/auth: '1.5.2'
  google/cloud-core: '1.33.0'
  google/cloud-storage: '1.14.0'
  google/crc32: '0.1.0'
  guzzlehttp/guzzle: '6.3.3'
  guzzlehttp/promises: '1.3.1'
  guzzlehttp/psr7: '1.6.1'
  helpscout/api: '2.4.0'
  http-interop/http-factory-guzzle: '1.0.0'
  incenteev/composer-parameter-handler: '2.1.3'
  jdorn/sql-formatter: '1.2.17'
  jean85/pretty-package-versions: '1.2'
  kreait/clock: '1.0.1'
  kreait/firebase-php: '4.32.0'
  kreait/firebase-tokens: '1.9.1'
  kreait/gcp-metadata: '1.0.1'
  ktamas77/firebase-php: '2.2.2'
  lcobucci/jwt: '3.3.1'
  league/flysystem: '1.0.55'
  lexik/jwt-authentication-bundle: '2.6.4'
  michelf/php-markdown: '1.8.0'
  monolog/monolog: '1.25.1'
  mtdowling/jmespath.php: '2.4.0'
  myclabs/deep-copy: '1.9.3'
  namshi/jose: '7.2.3'
  nelmio/cors-bundle:
    version: '1.5.6'
    message: 'Warning (minor severity): nelmio/cors-bundle does not have version that is fully compatible with PHP 7.3 (latest known 1.5.6)'
  nelmio/api-doc-bundle: '2.13.4'
  ocramius/package-versions: '1.5.1'
  ocramius/proxy-manager: '2.2.0'
  paragonie/random_compat: '0.0'
  phar-io/manifest: '1.0.3'
  phar-io/version: '2.0.1'
  php-amqplib/php-amqplib: '2.8.0'
  php-amqplib/rabbitmq-bundle:
    version: '1.14.4'
    message: 'Warning (minor severity): php-amqplib/rabbitmq-bundle does not have version that is fully compatible with PHP 7.3 (latest known 1.14.4)'
  php-cs-fixer/diff: '1.3.0'
  php-http/client-common: '2.0.0'
  php-http/curl-client: '2.0.0'
  php-http/discovery: '1.7.0'
  php-http/httplug: '2.0.0'
  php-http/message: '1.8.0'
  php-http/message-factory: '1.0.2'
  php-http/promise: '1.0.0'
  phpdocumentor/reflection-common: '2.0.0'
  phpdocumentor/reflection-docblock: '4.3.2'
  phpdocumentor/type-resolver: '1.0.1'
  phpspec/prophecy: '1.8.1'
  phpunit/php-code-coverage: '7.0.0'
  phpunit/php-file-iterator: '2.0.2'
  phpunit/php-text-template: '1.2.1'
  phpunit/php-timer: '2.1.2'
  phpunit/php-token-stream: '3.1.1'
  phpunit/phpunit: '8.0'
  psr/cache: '0.0'
  psr/container: '0.0'
  psr/http-client: '0.0'
  psr/http-factory: '0.0'
  psr/http-message: '0.0'
  psr/link: '0.0'
  psr/log: '0.0'
  psr/simple-cache: '0.0'
  ql/uri-template: '1.1.3'
  ralouphie/getallheaders: '3.0.3'
  ramsey/uuid: '3.8.0'
  raptor/php-migration-helper: '0.0'
  riverline/multipart-parser: '2.0.5'
  rize/uri-template:
    version: '0.3.2'
    message: 'Warning (minor severity): rize/uri-template does not have version that is fully compatible with PHP 7.3 (latest known 0.3.2)'
  sebastian/code-unit-reverse-lookup: '1.0.1'
  sebastian/comparator: '3.0.2'
  sebastian/diff: '3.0.2'
  sebastian/environment: '4.2.2'
  sebastian/exporter: '3.1.2'
  sebastian/global-state: '3.0.0'
  sebastian/object-enumerator: '3.0.3'
  sebastian/object-reflector: '1.1.1'
  sebastian/recursion-context: '3.0.0'
  sebastian/resource-operations: '2.0.1'
  sebastian/type: '1.0.0'
  sebastian/version: '2.0.1'
  sensio/distribution-bundle: '5.0.25'
  sensio/generator-bundle: '3.1.7'
  sensio/framework-extra-bundle: '5.4.1'
  sensiolabs/security-checker: '6.0.2'
  sentry/sdk: '2.0.4'
  sentry/sentry: '2.1.3'
  sentry/sentry-symfony: '3.1.0'
  shuber/curl: '0.0'
  skyeng/auth-bundle: '0.0'
  skyeng/common-bundle: '0.0'
  skyeng/php-lemmatizer: '1.0.3'
  superbalist/flysystem-google-storage: '7.2.1'
  swiftmailer/swiftmailer: '6.2.1'
  symfony/http-client: '4.3.4'
  symfony/http-client-contracts: '1.1.6'
  symfony/mime: '4.3.4'
  symfony/monolog-bundle: '3.1.2'
  symfony/phpunit-bridge: '3.4.31'
  symfony/polyfill-apcu: '1.12.0'
  symfony/polyfill-ctype: '1.12.0'
  symfony/polyfill-iconv: '1.12.0'
  symfony/polyfill-intl-icu: '1.12.0'
  symfony/polyfill-intl-idn: '1.12.0'
  symfony/polyfill-mbstring: '1.12.0'
  symfony/polyfill-php56: '0.0'
  symfony/polyfill-php70: '0.0'
  symfony/polyfill-php72: '0.0'
  symfony/polyfill-php73: '0.0'
  symfony/polyfill-util: '1.12.0'
  symfony/swiftmailer-bundle:
    version: '3.2.8'
    message: 'Warning (minor severity): symfony/swiftmailer-bundle does not have version that is fully compatible with PHP 7.3 (latest known 3.2.8)'
  symfony/symfony: '3.4.31'
  theseer/tokenizer: '1.1.3'
  twig/twig: '2.11.3'
  webmozart/assert: '1.5.0'
  welp/mailchimp-bundle: '1.2.3'
  willdurand/jsonp-callback-validator: '1.1.0'
  willdurand/negotiation: '2.3.1'
  zendframework/zend-code: '3.3.2'
  zendframework/zend-diactoros: '2.1.3'
  zendframework/zend-eventmanager: '3.2.1'

rules:
  heredoc:
    regexp: '/<<</'
    recommendation: 'Check that Heredoc/Nowdoc string does not contain closing identifier inside in the beginning of line'
    lines_after: 6
  pcre2:
    regexp: '/(^|(^|[^-])>|[^:>\w])preg_\w*\s*\(/'
    recommendation: 'Check that pattern corresponds PCRE2 syntax'
    lines_before: 3
    lines_after: 1
  continue:
    regexp: '/continue;/'
    recommendation: 'Check that continue is not inside switch, otherwise change to break or continue 2'
    lines_before: 6
  json_exception:
    regexp: '/(^|[^\w])JsonException($|[^\w])/'
    recommendation: 'Check that JsonException is not in the global namespace (now global JsonException is a part of PHP)'
    lines_before: 3
  json_throw_on_error:
    regexp: '/(^|[^\w])JSON_THROW_ON_ERROR($|[^\w])/'
    recommendation: 'Check that JSON_THROW_ON_ERROR is not in the global namespace (now global JSON_THROW_ON_ERROR is a part of PHP)'
    lines_before: 3
  static:
    regexp: '/\w::\$\w*\s*=\s*\&/'
    recommendation: 'Check that this is not static field assignment by reference (now they cannot be separated by assignment by reference)'
    lines_after: 3
  getimagesize:
    regexp: '/(^|(^|[^-])>|[^:>\w])getimagesize\s*\(/'
    recommendation: 'Check that value with key "mime" of getimagesize result is not compared to image/x-ms-bmp'
    lines_after: 3
  mb_ereg:
    regexp: '/(^|(^|[^-])>|[^:>\w])mb_ereg\w*\s*\(/'
    recommendation: 'Check usage of mb_ereg_-prefixed functions, now named captures are returned both using their group number and their name'
    lines_after: 4
  str_func:
    regexp: '/(^|(^|[^-])>|[^:>\w])strr?i?(pos|chr|str)\s*\([^,]*,\s*[^\s''"]/'
    recommendation: 'Check parameter $needle in functions strpos(), strrpos(), stripos(), strripos(), strstr(), strchr(), strrchr(), stristr(), now it should be string'
    lines_before: 3
  image2wbmp:
    regexp: '/(^|(^|[^-])>|[^:>\w])image2wbmp\s*\(/'
    recommendation: 'Replace image2wbmp() with imagewbmp()'
  filter_flag_scheme_required:
    regexp: '/(^|[^\w])FILTER_FLAG_SCHEME_REQUIRED($|[^\w])/'
    recommendation: 'Use FILTER_VALIDATE_URL without FILTER_FLAG_SCHEME_REQUIRED'
  filter_flag_host_required:
    regexp: '/(^|[^\w])FILTER_FLAG_HOST_REQUIRED($|[^\w])/'
    recommendation: 'Use FILTER_VALIDATE_URL without FILTER_FLAG_HOST_REQUIRED'
  case_insensitive_const:
    regexp: '/(^|(^|[^-])>|[^:>\w])define\s*\([^,\)]*,[^,\)]*,\s*true\s*\)/'
    recommendation: 'Check whether case insensitive const is defined. If so, replace with usual const declaration and check all usages'
  local_assert:
    regexp: '/function\s*assert\s*\(/'
    recommendation: 'Check whether assert is declared inside namespace, now it is forbidden, change function name'
  fgetss:
    regexp: '/(^|(^|[^-])>|[^:>\w])fgetss\s*\(/'
    recommendation: 'Replace fgetss with fgets and manual tag removal'
  gzgetss:
    regexp: '/(^|(^|[^-])>|[^:>\w])gzgetss\s*\(/'
    recommendation: 'Replace gzgetss with gzgets and manual tag removal'
  strip_tags_filter:
    regexp: '/[^\w]string.strip_tags[^\w]/'
    recommendation: 'Replace stream filter string.strip_tags with manual tag removal'
  mbregex_encoding:
    regexp: '/(^|(^|[^-])>|[^:>\w])mbregex_encoding\s*\(/'
    recommendation: 'Replace mbregex_encoding with mb_regex_encoding'
  mbsplit:
    regexp: '/(^|(^|[^-])>|[^:>\w])mbsplit\s*\(/'
    recommendation: 'Replace mbsplit with mb_split'
  mbereg:
    regexp: '/(^|(^|[^-])>|[^:>\w])mbereg\w*\s*\(/'
    recommendation: 'Replace mbereg-prefixed function with corresponding mb_ereg_-prefixed function'
