version: '7.2'

excluded:
  - var
  - vendor/cloudinary/cloudinary_php
  - vendor/composer
  - vendor/doctrine/annotations
  - vendor/doctrine/cache
  - vendor/doctrine/collections
  - vendor/doctrine/common
  - vendor/doctrine/data-fixtures
  - vendor/doctrine/dbal
  - vendor/doctrine/doctrine-bundle
  - vendor/doctrine/doctrine-cache-bundle
  - vendor/doctrine/doctrine-fixtures-bundle
  - vendor/doctrine/doctrine-migrations-bundle
  - vendor/doctrine/inflector
  - vendor/doctrine/lexer
  - vendor/doctrine/migrations
  - vendor/doctrine/orm
  - vendor/doctrine/persistence
  - vendor/doctrine/reflection
  - vendor/firebase/php-jwt
  - vendor/friendsofphp/php-cs-fixer
  - vendor/friendsofsymfony/rest-bundle
  - vendor/giggsey/libphonenumber-for-php
  - vendor/giggsey/locale
  - vendor/google/auth
  - vendor/google/cloud-core
  - vendor/google/cloud-storage
  - vendor/google/crc32
  - vendor/guzzlehttp/guzzle
  - vendor/guzzlehttp/promises
  - vendor/guzzlehttp/psr7
  - vendor/raptor/php-migration-helper
  - vendor/symfony/http-client
  - vendor/symfony/mime
  - vendor/symfony/monolog-bundle
  - vendor/symfony/phpunit-bridge
  - vendor/symfony/polyfill-ctype
  - vendor/symfony/polyfill-intl-idn
  - vendor/symfony/polyfill-mbstring
  - vendor/symfony/polyfill-php56
  - vendor/symfony/polyfill-php70
  - vendor/symfony/polyfill-php72
  - vendor/symfony/polyfill-php73
  - vendor/symfony/polyfill-util
  - vendor/symfony/swiftmailer-bundle
  - vendor/symfony/symfony

packages:
  cloudinary/cloudinary_php: '1.14.0'
  doctrine/annotations: '1.7.0'
  doctrine/cache: '1.8.0'
  doctrine/collections: '1.6.2'
  doctrine/common: '2.11.0'
  doctrine/data-fixtures: '1.3.2'
  doctrine/dbal: '2.9.2'
  doctrine/doctrine-bundle: '1.11.2'
  doctrine/doctrine-cache-bundle: '1.3.5'
  doctrine/doctrine-fixtures-bundle: '3.2.2'
  doctrine/doctrine-migrations-bundle: '1.3.2'
  doctrine/inflector: '1.3.0'
  doctrine/lexer: '1.1.0'
  doctrine/migrations: '1.8.1'
  doctrine/orm: '2.6.3'
  doctrine/persistence: '1.1.1'
  doctrine/reflection: '1.0.0'
  firebase/php-jwt: '5.0.0'
  friendsofphp/php-cs-fixer: '2.15.3'
  friendsofsymfony/rest-bundle: 'Warning (minor severity): friendsofsymfony/rest-bundle does not have version that is fully compatible with PHP 7.2 (latest known 2.5.0)'
  giggsey/libphonenumber-for-php: '8.10.19'
  giggsey/locale: '1.7.1'
  google/auth: '1.5.2'
  google/cloud-core: '1.33.0'
  google/cloud-storage: '1.14.0'
  google/crc32: '0.1.0'
  guzzlehttp/guzzle: '6.3.3'
  guzzlehttp/promises: '1.3.1'
  guzzlehttp/psr7: '1.6.1'
  incenteev/composer-parameter-handler: '2.1.3'
  jdorn/sql-formatter: '1.2.17'
  kreait/clock: '1.0.1'
  kreait/firebase-php: '4.32.0'
  kreait/firebase-tokens: '1.9.1'
  kreait/gcp-metadata: '1.0.1'
  ktamas77/firebase-php: '2.2.2'
  lcobucci/jwt: '3.3.1'
  league/flysystem: '1.0.55'
  lexik/jwt-authentication-bundle: '2.6.4'
  monolog/monolog: '1.25.1'
  mtdowling/jmespath.php: '2.4.0'
  myclabs/deep-copy: '1.9.3'
  namshi/jose: '7.2.3'
  nelmio/cors-bundle: 'Warning (minor severity): nelmio/cors-bundle does not have version that is fully compatible with PHP 7.2 (latest known 1.5.6)'
  ocramius/package-versions: '1.5.1'
  ocramius/proxy-manager: '2.2.0'
  paragonie/random_compat: 'Warning (minor severity): paragonie/random_compat should not be used with PHP 7.2'
  phar-io/manifest: '1.0.3'
  phar-io/version: '2.0.1'
  php-amqplib/php-amqplib: '2.8.0'
  php-amqplib/rabbitmq-bundle: '1.14.4'
  php-cs-fixer/diff: '1.3.0'
  phpdocumentor/reflection-common: '2.0.0'
  phpdocumentor/reflection-docblock: '4.3.2'
  phpdocumentor/type-resolver: '1.0.1'
  phpspec/prophecy: '1.8.1'
  phpunit/php-code-coverage: '7.0.0'
  phpunit/php-file-iterator: '2.0.2'
  phpunit/php-text-template: '1.2.1'
  phpunit/php-timer: '2.1.2'
  phpunit/php-token-stream: '3.1.1'
  phpunit/phpunit: '8.0'
  riverline/multipart-parser: '2.0.5'
  rize/uri-template: '0.3.2'
  sebastian/code-unit-reverse-lookup: '1.0.1'
  sebastian/comparator: '3.0.2'
  sebastian/diff: '3.0.2'
  sebastian/environment: '4.2.2'
  sebastian/exporter: '3.1.2'
  sebastian/global-state: '3.0.0'
  sebastian/object-enumerator: '3.0.3'
  sebastian/object-reflector: '1.1.1'
  sebastian/recursion-context: '3.0.0'
  sebastian/resource-operations: '2.0.1'
  sebastian/type: '1.0.0'
  sebastian/version: '2.0.1'
  sensio/distribution-bundle: '5.0.25'
  sensio/generator-bundle: '3.1.7'
  sensio/framework-extra-bundle: '3.0.29'
  sensiolabs/security-checker: '6.0.2'
  sentry/sentry: '1.10.0'
  sentry/sentry-symfony: '0.8.8'
  superbalist/flysystem-google-storage: '7.2.1'
  swiftmailer/swiftmailer: '5.4.12'
  symfony/http-client: '4.3.4'
  symfony/mime: '4.3.4'
  symfony/monolog-bundle: '3.1.2'
  symfony/phpunit-bridge: '3.4.31'
  symfony/polyfill-ctype: '1.12.0'
  symfony/polyfill-intl-idn: '1.12.0'
  symfony/polyfill-mbstring: '1.12.0'
  symfony/polyfill-php56: 'Warning (minor severity): symfony/polyfill-php56 should not be used with PHP 7.2'
  symfony/polyfill-php70: 'Warning (minor severity): symfony/polyfill-php70 should not be used with PHP 7.2'
  symfony/polyfill-php72: 'Warning (minor severity): symfony/polyfill-php72 should not be used with PHP 7.2'
  symfony/polyfill-php73: '1.12.0'
  symfony/polyfill-util: '1.12.0'
  symfony/swiftmailer-bundle: 'Warning (minor severity): symfony/swiftmailer-bundle does not have version that is fully compatible with PHP 7.2 (latest known 3.2.8)'
  symfony/symfony: '3.4.31'
  theseer/tokenizer: '1.1.3'
  twig/twig: '2.11.3'
  webmozart/assert: '1.5.0'
  willdurand/jsonp-callback-validator: '1.1.0'
  willdurand/negotiation: '2.3.1'
  zendframework/zend-code: '3.3.2'
  zendframework/zend-eventmanager: '3.2.1'

rules:
  get_class:
    regexp: '/(^|(^|[^-])>|[^:>\w])get_class\s*\(/'
    recommendation: 'Check that parameter of get_class() cannot be null'
    lines_before: 4
  count:
    regexp: '/(^|(^|[^-])>|[^:>\w])count\s*\(/'
    recommendation: 'Check that parameter of count() is always countable'
    lines_before: 4
  array_unique:
    regexp: '/(^|(^|[^-])>|[^:>\w])array_unique\s*\(/'
    recommendation: 'Check that result of array_unique with sort_flags = SORT_STRING does not use keys for non-associative arrays (it may be reindexed)'
    lines_after: 4
  is_object:
    regexp: '/(^|(^|[^-])>|[^:>\w])is_object\s*\(/'
    recommendation: 'Check that parameter of is_object() cannot be __PHP_Incomplete_Class (now it returns TRUE instead of FALSE)'
    lines_before: 4
  number_format:
    regexp: '/(^|(^|[^-])>|[^:>\w])number_format\s*\(/'
    recommendation: 'Check that result of number_format is not compared with "-0"'
    lines_after: 2
  gettype:
    regexp: '/(^|(^|[^-])>|[^:>\w])gettype\s*\(/'
    recommendation: 'Check that result of gettype is not compared with "unknown type" (for closed resources now it returns "resource (closed)")'
    lines_after: 2
  bcmod:
    regexp: '/(^|(^|[^-])>|[^:>\w])bcmod\s*\(/'
    recommendation: 'Check that bcmod result is not compared to int (now result is not rounded)'
    lines_after: 2
  hash_functions:
    regexp: '/(^|(^|[^-])>|[^:>\w])hash_(hmac(_file)?|pbkdf2)\s*\(/'
    recommendation: 'Check that hash_hmac, hash_hmac_file, hash_pbkdf2 function do not use one of the following algorithms adler32, crc32, crc32b, fnv132, fnv1a32, fnv164, fnv1a64, joaat'
    lines_before: 2
  hash_init:
    regexp: '/(^|(^|[^-])>|[^:>\w])hash_init\s*\([^,]*,\s*HASH_HMAC/'
    recommendation: 'Check that hash_init with HASH_HMAC parameter does not use one of the following algorithms adler32, crc32, crc32b, fnv132, fnv1a32, fnv164, fnv1a64, joaat'
    lines_before: 2
  rand:
    regexp: '/(^|(^|[^-])>|[^:>\w])(mt_)?rand\s*\(/'
    recommendation: 'If rand or mt_rand is called with fixed seed, resulting sequence after migration may differ from current'
    lines_before: 2
    lines_after: 2
  date_parse_from_format:
    regexp: '/(^|(^|[^-])>|[^:>\w])date_parse_from_format\s*\(/'
    recommendation: 'Check, that value for key "zone" in the result of date_parse_from_format is not used (now it contains seconds with inverted sign instead of minutes)'
    lines_after: 4
  autoload:
    regexp: '/(^|(^|[^-])>|[^:>\w])__autoload\s*\(/'
    recommendation: 'Replace __autoload() with spl_autoload_register()'
  png2wbmp:
    regexp: '/(^|(^|[^-])>|[^:>\w])png2wbmp\s*\(/'
    recommendation: 'Replace png2wbmp() with imagecreatefrompng() and imagewbmp()'
  jpeg2wbmp:
    regexp: '/(^|(^|[^-])>|[^:>\w])jpeg2wbmp\s*\(/'
    recommendation: 'Replace jpeg2wbmp() with imagecreatefromjpeg() and imagewbmp()'
  unset:
    regexp: '/\(unset\)/'
    recommendation: 'Replace (unset) cast with call of unset or just NULL'
  parse_str:
    regexp: '/(^|(^|[^-])>|[^:>\w])parse_str\s*\(/'
    recommendation: 'Check whether parse_str is called with second parameter, now it is necessary'
  gmp_random:
    regexp: '/(^|(^|[^-])>|[^:>\w])gmp_random\s*\(/'
    recommendation: 'Replace gmp_random() with gmp_random_bits() or gmp_random_range()'
  each:
    regexp: '/(^|(^|[^-])>|[^:>\w])each\s*\(/'
    recommendation: 'Replace each() with foreach()'
  assert:
    regexp: '/(^|(^|[^-])>|[^:>\w])assert[\s\(]/'
    recommendation: 'Check whether assert() is called with string argument. If so, replace with direct call and fix zend.assertions in ini-file'
    lines_before: 3
  php_errormsg:
    regexp: '/\$php_errormsg[^\w]/'
    recommendation: 'Replace $php_errormsg with error_get_last()'
  create_function:
    regexp: '/(^|(^|[^-])>|[^:>\w])create_function\s*\(/'
    recommendation: 'Replace create_function with anonymous function declaration'
  errcontext:
    regexp: '/\$errcontext[^\w]/'
    recommendation: 'Remove usage of $errcontext, use debugger instead'
  read_exif_data:
    regexp: '/(^|(^|[^-])>|[^:>\w])read_exif_data\s*\(/'
    recommendation: 'Replace read_exif_data with exif_read_data'
  intl_idna_variant_2003:
    regexp: '/(^|[^\w])INTL_IDNA_VARIANT_2003($|[^\w])/'
    recommendation: 'Replace INTL_IDNA_VARIANT_2003 with INTL_IDNA_VARIANT_UTS46'
  setup:
    regexp: '/function\s*setUp(BeforeClass)?\s*\(\s*\)[^:]*$/'
    recommendation: 'Add void return type hint to setUp or setUpBeforeClass'
  tear_down:
    regexp: '/function\s*tearDown(AfterClass)?\s*\(\s*\)[^:]*$/'
    recommendation: 'Add void return type hint to tearDown or tearDownBeforeClass'
  assert_conditions:
    regexp: '/function\s*assert(Pre|Post)Conditions\s*\(\s*\)[^:]*$/'
    recommendation: 'Add void return type hint to assertPreConditions or assertPostConditions'
  on_successful_test:
    regexp: '/function\s*onNotSuccessfulTest\s*\(\s*\)[^:]*$/'
    recommendation: 'Add void return type hint to onNotSuccessfulTest'
  assert_internal_type:
    regexp: '/(^|(^|[^-])>|[^:>\w])assert(Not)?InternalType\s*\(/'
    recommendation: 'Replace assertInternalType and assertNotInternalType methods with more specific methods'
  assert_array_subset:
    regexp: '/(^|(^|[^-])>|[^:>\w])assertArraySubset\s*\(/'
    recommendation: 'Remove assertArraySubset usage, refactor to manual check'
  assert_equals:
    regexp: '/(^|(^|[^-])>|[^:>\w])assert(Not)?Equals\s*\([^,]*,[^,]*,[^,]*,/'
    recommendation: 'Replace usage of optional arguments of assertEquals and assertNotEquals with more specific assertions'
  assert_attribute:
    regexp: '/(^|(^|[^-])>|[^:>\w])assertAttribute\w*\s*\(/'
    recommendation: 'Replace usage of assertAttribute-prefixed methods with manual processing'
  attribute:
    regexp: '/(^|(^|[^-])>|[^:>\w])attribute(EqualTo)?\s*\(/'
    recommendation: 'Replace usage of attribute and attributeEqualTo methods with manual processing'
  read_attribute:
    regexp: '/(^|(^|[^-])>|[^:>\w])readAttribute\s*\(/'
    recommendation: 'Replace usage of readAttribute method with manual processing'
  get_attribute:
    regexp: '/(^|(^|[^-])>|[^:>\w])get(Static|Object)Attribute\s*\(/'
    recommendation: 'Replace usage of getStaticAttribute or getObjectAttribute methods with manual processing'
  assert_contains:
    regexp: '/(^|(^|[^-])>|[^:>\w])assert(Not)?Contains\w*\s*\(/'
    recommendation: 'Replace usage of assertContains and assertNotContains methods with more specified method (for string or for array)'
  test_listener:
    regexp: '/(^|(^|[^-])>|[^:>\w])TestListener($|[^\w])/'
    recommendation: 'Remove usage of TestListener'
  expected_exception_annotation:
    regexp: '/@expectedException/'
    recommendation: 'Remove usage of expectedException-prefixed annotations'
